// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as FilerReader from "../Vendor/FilerReader.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function getText(ev) {
  return ev.target.value;
}

function getFloat(ev) {
  return Core__Option.getOr(Core__Float.fromString(ev.target.value), 0);
}

function getInt(ev) {
  return Core__Option.getOr(Core__Int.fromString(undefined, ev.target.value), 0);
}

function getFile(ev) {
  return Belt_Array.get(ev.target.files, 0);
}

function fileAsDataURL(file, cb) {
  FilerReader.fileToDataUrl(file, cb);
}

function Input(props) {
  var __className = props.className;
  var onChange = props.onChange;
  var __value = props.value;
  var label = props.label;
  var __type_ = props.type_;
  var type_ = __type_ !== undefined ? __type_ : "text";
  var value = __value !== undefined ? __value : "";
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("label", {
                      children: label,
                      className: "block text-xs font-medium text-gray-900",
                      htmlFor: label
                    }),
                JsxRuntime.jsx("input", {
                      className: "block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6 focus:outline-0",
                      id: label,
                      name: label,
                      type: type_,
                      value: value,
                      onChange: (function (ev) {
                          onChange(ev);
                        })
                    })
              ],
              className: "rounded-md px-3 pb-1.5 pt-2.5 shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600 " + className
            });
}

var make = Input;

export {
  getText ,
  getFloat ,
  getInt ,
  getFile ,
  fileAsDataURL ,
  make ,
}
/* react/jsx-runtime Not a pure module */
