// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function Select(props) {
  var __value = props.value;
  var onChange = props.onChange;
  var __className = props.className;
  var label = props.label;
  var className = __className !== undefined ? __className : "";
  var value = __value !== undefined ? __value : "__none";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("label", {
                      children: label,
                      className: "block text-xs font-medium text-gray-900",
                      htmlFor: label
                    }),
                JsxRuntime.jsxs("select", {
                      children: [
                        JsxRuntime.jsx("option", {
                              children: "Select a font",
                              value: "__none"
                            }, "__none"),
                        props.options.map(function (param) {
                              var key = param[0];
                              return JsxRuntime.jsx("option", {
                                          children: param[1],
                                          value: key
                                        }, key);
                            })
                      ],
                      className: "relative cursor-default rounded-md bg-white py-1.5 pl-3 pr-10 text-left text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:outline-none sm:text-sm sm:leading-6",
                      name: "select",
                      value: value,
                      onChange: (function (ev) {
                          var value = Belt_Option.getExn(Core__JSON.Decode.string(ev.target.value));
                          if (value !== "__none") {
                            return onChange(value);
                          }
                          
                        })
                    })
              ],
              className: "rounded-md px-3 pb-1.5 pt-2.5 shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600 " + className
            });
}

var make = Select;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
