// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Makerjs from "makerjs";
import * as Opentype from "./Vendor/Opentype.res.mjs";
import OpentypeLayout from "opentype-layout";

function composeModel(text, letterSpacingOpt, font, fontSizeOpt, lineHeightOpt, alignOpt, canvasWidthOpt) {
  var letterSpacing = letterSpacingOpt !== undefined ? letterSpacingOpt : 0;
  var fontSize = fontSizeOpt !== undefined ? fontSizeOpt : 16;
  var lineHeight = lineHeightOpt !== undefined ? lineHeightOpt : Opentype.default_lineHeight;
  var align = alignOpt !== undefined ? alignOpt : "left";
  var canvasWidth = canvasWidthOpt !== undefined ? canvasWidthOpt : 300;
  var model = new (Makerjs.models.Text)(font, "", fontSize);
  var scale = 1.0 / font.unitsPerEm * fontSize;
  var lineHeight$1 = lineHeight * font.unitsPerEm;
  var width = canvasWidth / scale;
  var layout = OpentypeLayout(font, text, Opentype.Layout.Options.make(align, lineHeight$1, width, letterSpacing));
  layout.glyphs.forEach(function (glyph, i) {
        var character = Makerjs.models.Text.glyphToModel(glyph.data, fontSize);
        var newOrigin = Makerjs.point.scale(glyph.position, scale);
        character.origin = newOrigin;
        Makerjs.model.addModel(model, character, i);
      });
  return model;
}

export {
  composeModel ,
}
/* makerjs Not a pure module */
